### ISSUE TITLE
deps: Wrong deps resolve by context

### ISSUE THREAD

**Issue by tadatuta** [enb-bem/enb-bem-techs#158] opened 2015-06-26 20:55 UTC
When building deps bundle with `deps` tech of `enb-bem-techs@1.0.4` it treats `shouldDeps: { mod : 'init' }` in `i-bem__dom.deps.js` as `i-bem_init` but `i-bem__dom_init` expected.

**Comment by blond** [comment] 2015-07-09 21:13
duplicate of #112

**Closed by blond** 2015-07-09 21:13 UTC
Labels: backlog, bug, duplicate, prio:normal
