### ISSUE TITLE
deps: Parse mods as array

### ISSUE THREAD

**Issue by tadatuta** [enb-bem/enb-bem-techs#159] opened 2015-06-26 21:16 UTC
Not sure if it should work at all but in `bem-componens` [there's](https://github.com/bem/bem-components/tree/0a060e7dea45790d162fdbb1f09e08d3e8d705cb)
```js
shouldDeps : {
    mods : ['disabled', 'focused'],
}
```
which results in
```
  'input_0',
  'input_1',
  'input_0_disabled',
  'input_1_focused'
```
now.

**Comment by tavriaforever** [comment] 2015-06-29 18:15
I never saw deps with mods writing in array way, it`s strange.

**Comment by blond** [comment] 2015-07-09 21:17
duplicate of #113

**Closed by blond** 2015-07-09 21:17 UTC
Labels: backlog, bug, prio:normal
